num_players: 3
num_factories: 7
tile_colors:
  - "blue"
  - "red"
  - "yellow"
  - "black"
  - "white"
wall_pattern:
  - [blue, yellow, red, black, white] 
  - [white, blue, yellow, red, black]
  - [black, white, blue, yellow, red]
  - [red, black, white, blue, yellow]
  - [yellow, red, black, white, blue]
pattern_line_size: 5 
