num_players: 2
num_factories: 5
tile_colors:
  - "blue"
  - "red"
  - "yellow"
  - "black"
  - "white"
wall_pattern:
  - [None, None, None, None, None] 
  - [None, None, None, None, None]
  - [None, None, None, None, None]
  - [None, None, None, None, None]
  - [None, None, None, None, None]
pattern_line_size: 5 
